# Generated by Django 4.2.2 on 2023-09-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='name', max_length=100)),
                ('quantidade', models.IntegerField(db_column='quantity')),
                ('valor', models.FloatField(db_column='price')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='name', max_length=100)),
                ('quantidade', models.IntegerField(db_column='quantity')),
                ('valor', models.FloatField(db_column='price')),
            ],
        ),
    ]
