# Generated by Django 3.2.21 on 2023-10-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='another_expenses',
            field=models.FloatField(blank=True, db_column='another_expenses', verbose_name='Outros Custos (R$):'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marketplace_tax',
            field=models.FloatField(blank=True, db_column='marketplace_tax', verbose_name='Taxa de Comissão em Marketplace %:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='name', max_length=100, verbose_name='Nome do Produto:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit',
            field=models.FloatField(blank=True, db_column='profit', verbose_name='Lucro Desejado (R$):'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, db_column='quantity', verbose_name='Quantidade Desejada:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='taxes',
            field=models.FloatField(blank=True, db_column='taxes', verbose_name='Impostos:'),
        ),
    ]
