# Generated by Django 4.2.2 on 2023-09-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.FloatField(db_column='salary')),
                ('horas', models.FloatField(db_column='hours')),
                ('tempo', models.CharField(db_column='time', max_length=100)),
            ],
        ),
    ]
