# Generated by Django 3.2.21 on 2024-01-07 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20231022_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='Nome do Produto:')),
                ('another_expenses', models.FloatField(blank=True, db_column='another_expenses', verbose_name='Outros Custos (R$):')),
                ('incalculable_expenses', models.FloatField(blank=True, db_column='incalculable_expenses', verbose_name='Custos Incalculáveis (R$):')),
                ('marketplace_tax', models.FloatField(blank=True, db_column='marketplace_tax', verbose_name='Taxa de Comissão em Marketplace %:')),
                ('taxes', models.FloatField(blank=True, db_column='taxes', verbose_name='Impostos %:')),
                ('quantity', models.IntegerField(blank=True, db_column='quantity', verbose_name='Quantidade Desejada (UNI):')),
                ('profit', models.FloatField(blank=True, db_column='profit', verbose_name='Lucro Desejado (R$):')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(choices=[('KG', 'Kg'), ('GRAMAS', 'g'), ('L', 'l'), ('ML', 'Ml'), ('UNIDADES', 'Unidade(s)')], max_length=8, verbose_name='Medida da Embalagem:'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_column='name', max_length=100, verbose_name='Nome do Insumo:'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(db_column='price', verbose_name='(R$) Preço:'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(db_column='quantity', verbose_name='Quantidade em Embalagem Fechada:'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='hours',
            field=models.FloatField(db_column='hours', verbose_name='Total de Horas trabalhada por dia:'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='name',
            field=models.CharField(db_column='name', max_length=100, verbose_name='Nome da Mão de Obra:'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='salary',
            field=models.FloatField(db_column='salary', verbose_name='Salário do Mês:'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='time',
            field=models.CharField(choices=[('Hora', 'Hora'), ('Minutos', 'Minutos'), ('Segundos', 'Segundos'), ('Dias', 'Dias')], max_length=15, verbose_name='Total de Dias trabalhados na semana:'),
        ),
        migrations.AlterField(
            model_name='percentingredient',
            name='measure',
            field=models.CharField(choices=[('KG', 'Kg'), ('GRAMAS', 'g'), ('L', 'l'), ('ML', 'Ml'), ('UNIDADES', 'Unidade(s)')], max_length=8, verbose_name='Medida do Pacote:'),
        ),
        migrations.CreateModel(
            name='PercentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, db_column='quantity', verbose_name='Quantidade Desejada (UNI):')),
                ('combo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.combo')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
    ]
