# Generated by Django 3.2.21 on 2023-09-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230920_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ingredient')),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.labor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.material')),
            ],
        ),
    ]
