# Generated by Django 3.2.21 on 2024-01-07 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240107_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='Nome da Taxa:')),
                ('percent', models.FloatField(db_column='percent', verbose_name='Porcentagem do Desconto:')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
